### PR TITLE
use python integers in a lot of places instead of 64 bit integers

### PR DESCRIPTION
**Pull request by alexanderrgriffing**
The dataset module now uses numpy instead of torch. Most datasets are now created with Python integers, so you can add bigger numbers that would overflow 64 bits. It still uses small integers for factoring because of how the sieve worked.

### CODE REVIEW

**Comment by thomasahle** [comment]
This is great, thanks!
How fast is it compared to the torch version?
Are there any downsides?

**Comment by alexanderrgriffing** [comment]
> How fast is it compared to the torch version?

For 14 digit dataset generation with `--kind=hybrid --hidden-size=64 --op=add` the 64 bit integer torch version takes 3 seconds and the Python integer numpy version takes 19 seconds on my computer.

**Comment by alexanderrgriffing** [comment]
It's faster now, down from 19 seconds to 10 seconds. It's still slower than sampling 64-bit integers.

**Comment by alexanderrgriffing** [comment]
> Are there any downsides?

None that I can think of, other than it's maybe 3 times slower in the data sampling phase.

**Comment by thomasahle** [comment]
If you don't need high precision, is it still the same speed as the pytorch version?
Maybe there can be a `--multiprecision` flag, or the code can detect automatically what it's needed?

**Comment by alexanderrgriffing** [comment]
> If you don't need high precision, is it still the same speed as the pytorch version?

The update makes it almost the same, like 3.7 seconds vs 3 seconds.

> Maybe there can be a `--multiprecision` flag, or the code can detect automatically what it's needed?

It now uses a `--preferred-dtype` flag which defaults to `int64` and you can pass `object` to make it use Python style big integers.

It's not tested extensively because there are lots of possible combinations of flags, a lot of them are slow, and there weren't any regression tests.

**Pull request merged**
